bisasesama/urls.py
from django.contrib import admin
from django.urls import path, include
import beranda.urls as beranda

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('trigger_dua/', include('trigger_dua.urls', namespace='trigger_dua')),
    path('trigger_tiga/', include('trigger_tiga.urls', namespace='trigger_tiga')),
    path('pengguna/', include('pengguna.urls', namespace='pengguna')),
    path('trigger_empat/', include('trigger_empat.urls', namespace='trigger_empat')),
    path('login/', include('login.urls', namespace='login')),
    path('trigger_lima/', include('trigger_lima.urls', namespace='trigger_lima')),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = [
    path("", login, name="login"),
    path("logout/", logout, name="logout"),

]
    # path("form_donasi/", form_donasi, name="form_donasi"),
    # path("donasi/read_donasi", read_donasi, name="read_donasi"),
    # path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),

pengguna/urls.py
from django.urls import path
from .views import *

app_name = 'pengguna'

urlpatterns = [
    path("register", register, name="register"),
    path("admin", form_admin, name="admin"),
    path("penggalang_dana", form_pd, name="penggalang_dana"),
    path("penggalang_dana/individu", form_pd_individu, name="pd_individu"),
    path("penggalang_dana/organisasi", form_pd_organisasi, name="pd_organisasi"),
    path("profil_pengguna", profil_pengguna, name="profil-pengguna"),
    path("daftar-pengguna-admin", read_daftar_pengguna_admin, name="daftar-pengguna-admin"),
    path("daftar-pengguna-admin-afterverif", read_daftar_pengguna_admin_afterverif, name="daftar-pengguna-admin-afterverif"),
    path("profil-pengguna-individu-adminview", profil_pengguna_individu_adminview, name="profil-pengguna-individu-adminview"),
    path("profil-pengguna-organisasi-adminview", profil_pengguna_organisasi_adminview, name="profil-pengguna-organisasi-adminview"),
    path("daftar-pengguna-admin-verif", verifikasi_pengguna, name="daftar-pengguna-admin-verif"),
    path("logout", logout, name = "logout"),
    path("login", login, name = "login"),
    


]

trigger_dua/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_dua'

urlpatterns = [
    path("form_kategori/", form_kategori, name="form_kategori"),
    path("form_kategori/create_pasien", form_pasien, name="form_pasien"),
    path("form_kategori/cek_pasien", cek_pasien, name="cek_pasien"),
    path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),
    path("penggalangan_dana/detail", read_pdd, name="read_pdd"),
    path("penggalangan_dana/create", form_penggalangan_dana, name="create_pdd"),
    path("penggalangan_dana/delete/", delete_penggalangan_dana, name="delete_pdd"),
    path("penggalangan_dana/cairkan", cairkan_pdd, name="cairkan_pdd"),
    path("komorbid/create/", create_komorbid, name="create_komorbid"),
    path("komorbid/update/(?P<id>[^/]+)$/(?P<penyakit>[^/]+)$/", update_komorbid, name="update_komorbid"),
    path("komorbid/delete/(?P<id>[^/]+)$/(?P<komorbid>[^/]+)$/", delete_komorbid, name="delete_komorbid"),
    path("komorbid/", read_komorbid, name="read_komorbid"),
]

trigger_empat/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_empat'

urlpatterns = [
    path("penggalangan_dana_POV_Pengguna/", cek_penggalangan_dana, name="read_halaman_penggalangan_dana"),
    path("form_donasi/", form_donasi, name="form_donasi"),
    path("donasi/read_donasi", read_donasi, name="read_donasi"),
    path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),
    path('tambah_Wishlist',tambah_wishlist, name= 'tambah_wishlist'),
    path('delete_wishlist', delete_wishlist_donasi, name = 'delete_wishlist' ),
    # path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    # path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    # path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),  
]

trigger_tiga/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_tiga'

urlpatterns = [
    path("daftar-penggalangan-dana-admin", read_daftar_penggalangan_dana_admin, name="daftar-penggalangan-dana-admin"),
    path("daftar-afterverif-penggalangan-dana-admin", read_afterverif_penggalangan_dana_admin, name="daftar-afterverif-penggalangan-dana-admin"),
    path("detail1-daftar-penggalangan-dana", detail1_daftar_penggalangan_dana, name="detail1-daftar-penggalangan-dana"),
    path("detail2-daftar-penggalangan-dana", detail2_daftar_penggalangan_dana, name="detail2-daftar-penggalangan-dana"),
    path("update-penggalangan-dana", form_update_penggalangan_dana, name="form-update-penggalangan-dana"),
    path("form-verifikasi-penggalangan-dana", form_verifikasi_penggalangan_dana, name="form-verifikasi-penggalangan-dana"),
    path("read-kategori-penggalangan-dana-admin", read_kategori_penggalangan_dana_admin, name="read-kategori-penggalangan-dana-admin"),
    path("form-create-kategori-penggalangan-dana", form_create_kategori_penggalangan_dana, name="form-create-kategori-penggalangan-dana"),
    path("form-update-kategori-penggalangan-dana", form_update_kategori_penggalangan_dana, name="form-update-kategori-penggalangan-dana"),

]

pengguna/views.py
from django.db import connection
from django.shortcuts import render, redirect
from pengguna.forms import *

def cursor_fetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

def pengguna(function):
    def wrapper(request, *args, **kwargs):
        email = request.session.get('email')
        if email is None:
            return redirect('/login/')
        else:
            return function(request, *args, **kwargs)
    return wrapper

def admin(function):
    def wrapper(request, *args, **kwargs):
        email = request.session.get('email')
        if email is None:
            return redirect('/login/')
        else:
            return function(request, *args, **kwargs)
    return wrapper

def tidak_ada_pengguna (function):
    def wrapper(request, *args, **kwargs):
        email = request.session.get('email')
        if email is not None:
            return redirect('/profile_pengguna/')
        else:
            return function(request, *args, **kwargs)
    return wrapper

def cek_role(email):
    with connection.cursor() as cursor:
        for i in ["ADMIN", "PENGGALANG_DANA", "INDIVIDU", "ORGANISASI"]:
            cursor.execute(
                f"SELECT * FROM {i} WHERE email=%s LIMIT 1;",
                [email])
            if cursor.fetchone() is not None:
                return i

def dapatkan_role(email, role):
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT * FROM {role} WHERE email=%s LIMIT 1;",
            [email])
        return cursor.fetchone()

def dapatkan_pd_donasi(email):
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT * FROM PENGGALANGAN_DANA_PD JOIN KATEGORI as PDK, INDIVIDU as I, DONASI as D WHERE I.email=%s AND I.email=D.email AND D.idPD=PDK.id;",
            [email]
        )
        return cursor.fetchone()

def input_session(request, email, nama):
    request.session['email'] = email
    request.session['nama'] = nama
    request.session['role'] = dapatkan_role(email)


@tidak_ada_pengguna
def login(request):
    if request.method == 'POST':        # Method post untuk mem-post data yang kita masukkan, untuk kemudian di-validasi
        form = LoginForm(request.POST)
        if form.is_valid():             # Jika form valid -> maka:
            with connection.cursor() as cursor:
                # Mengambil data penggalang_dana yang sesuai dengan email yang telah di-input oleh user
                cursor.execute(
                    "SELECT * FROM PENGGALANG_DANA WHERE email=%s LIMIT 1;",
                    [form.cleaned_data.get('email')])                           
                data = cursor.fetchone()                # Menyimpan semua data tersebut ke dalam variabel 'data'
            input_session(request, form.cleaned_data.get('email'), data[3])
            return redirect('/profile_pengguna/')       # Setelah berhasil login, langsung diarahkan ke halaman profil pengguna user tersebut
    
    elif request.method == 'GET':   
        form = LoginForm()
    context = {'form': form}        # Dengan method GET, semua data login yang telah ada dimasukkan ke dalam context
                                    # dengan variable 'form'.
    return render(request, "login.html", context)       # Data form tersebut kemudian di-render ke 

@tidak_ada_pengguna
def register(request):
    if request.method == 'POST':
        form = PilihRoleForm(request.POST)
        if form.is_valid():
            alamat_url = {'ADMIN': '/admin/',
                       'PENGGALANG_DANA': '/penggalang_dana/',
                       'INDIVIDU': '/penggalang_dana/individu/',
                       'ORGANISASI': '/penggalang_dana/organisasi/'}
            return redirect(alamat_url[form.cleaned_data.get('peran')])
    elif request.method == 'GET':
        form = PilihRoleForm()
    context = {'form': form}
    return render(request, 'register_role.html', context)

@tidak_ada_pengguna
def form_admin(request):
    if request.method == 'POST':
        form = AdminForm(request.POST)
        if form.is_valid():
            form.save()
            nama = form.cleaned_data.get('nama')
            input_session(request, form.cleaned_data.get('email'), nama)
            return redirect('/profile_pengguna/')
    elif request.method == 'GET':
        form = AdminForm()
    context = {'form': form}
    return render(request, 'form_admin.html', context)

@tidak_ada_pengguna
def form_pd(request):
    if request.method == 'POST':
        form = PenggalangDanaForm(request.POST)
        if form.is_valid():
            form.save()
            nama = form.cleaned_data.get('nama')
            input_session(request, form.cleaned_data.get('email'), nama)
            return redirect('/profile_pengguna/')
    elif request.method == 'GET':
        form = PenggalangDanaForm()
    context = {'form': form}
    return render(request, 'form_penggalang_dana.html', context)

@tidak_ada_pengguna
def form_pd_individu(request):
    if request.method == 'POST':
        form = IndividuForm(request.POST)
        if form.is_valid():
            form.save()
            nama = form.cleaned_data.get('nama')
            input_session(request, form.cleaned_data.get('email'), nama)
            return redirect('/profile_pengguna/')
    elif request.method == 'GET':
        form = IndividuForm()
    context = {'form': form}
    return render(request, 'form_pd_individu.html', context)

@tidak_ada_pengguna
def form_pd_organisasi(request):
    if request.method == 'POST':
        form = OrganisasiForm(request.POST)
        if form.is_valid():
            form.save()
            nama = form.cleaned_data.get('nama')
            input_session(request, form.cleaned_data.get('email'), nama)
            return redirect('/profile_pengguna/')
    elif request.method == 'GET':
        form = OrganisasiForm()
    context = {'form': form}
    return render(request, 'form_pd_organisasi.html', context)

@pengguna
def profil_pengguna(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM PENGGALANG_DANA WHERE email=%s",
                       [request.session.get("email")])
        data_pengguna = cursor.fetchone()
        role_pengguna = dapatkan_role(
            request.session.get("email"),
            request.session.get("role"))
    context = {'user': data_pengguna, 'role': role_pengguna}
    
    if request.session.get('role') == 'INDIVIDU':
        context['data_pd_donasi'] = dapatkan_pd_donasi(context['user'][0])
    return render(request, 'profil_pengguna.html', context)

@pengguna
def profil_pengguna_individu_adminview(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM INDIVIDU WHERE email=%s",
                       [request.session.get("email")])
        data_pengguna = cursor.fetchone()
        role_pengguna = dapatkan_role(
            request.session.get("email"),
            request.session.get("role"))
    context = {'user': data_pengguna, 'role': role_pengguna}
    return render(request, 'profil_pengguna_individu_adminview.html',context)

@pengguna
def profil_pengguna_organisasi_adminview(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM ORGANISASI WHERE email=%s",
                       [request.session.get("email")])
        data_pengguna = cursor.fetchone()
        role_pengguna = dapatkan_role(
            request.session.get("email"),
            request.session.get("role"))
    context = {'user': data_pengguna, 'role': role_pengguna}
    return render(request, 'profil_pengguna_organisasi_adminview.html',context)

# Admin only page. Pengguna cannot access
@pengguna
def read_daftar_pengguna_admin(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT email, nama, jenis, status_verifikasi FROM PENGGALANG_DANA;")
        data_pengguna = cursor_fetchall(cursor)
    context = {'data': data_pengguna}
    return render(request, 'read_daftar_pengguna_admin.html', context)

def verifikasi_pengguna(request):
    with connection.cursor() as cursor:
        # name = id_u with the value of {{ d.email }}
        cursor.execute("UPDATE PENGGALANG_DANA SET status_verifikasi='VERIFIED' WHERE email=%s;", [request.GET.get('id_u')])
        return redirect('pengguna:profil-pengguna-admin-verif')

@pengguna
def read_daftar_pengguna_admin_afterverif(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT email, nama, jenis, status_verifikasi "
                       "FROM PENGGALANG_DANA "
                       "WHERE status_verifikasi = 'VERIFIED';")
        data_pengguna= cursor_fetchall(cursor)
    context = {'data': data_pengguna}
    return render(request, 'read_daftar_pengguna_admin_afterverif.html',context)

def logout(request):
    request.session.flush()
    return redirect('/')

pengguna/templates/form_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}FORM PENDAFTARAN ADMIN{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>FORM PENDAFTARAN ADMIN</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'pengguna : admin' %}" method="POST">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            </div>
            {% endif %}
    
            <div class="form-group row">

                <h4>email:</h4>
                {% if form.email.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.email.errors }}
                </div>
                {% endif %}

                <div class="input-group mb-4">
                    <!-- <input class="form-control" type="text" aria-label="default input example" required> -->
                    {{form.email}}
                </div>

                <h4>Password:</h4>
                {% if form.password.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.password.errors }}
                </div>
                {% endif %}

                <div class="input-group mb-4">
                    <!-- <input class="form-control" type="text" aria-label="default input example" required> -->
                    {{form.Password}}
                </div>

                <h4>Nama:</h4>
                {% if form.nama_lengkap.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.nama_lengkap.errors }}
                </div>
                {% endif %}

                <div class="input-group mb-4">
                    <!-- <input class="form-control" type="text" aria-label="default input example" required> -->
                    {{form.nama_lengkap}}
                </div>

                <h4>Nomor HP:</h4>
                {% if form.nomor_hp.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.nomor_hp.errors }}
                </div>
                {% endif %}

                <div class="input-group mb-4">
                    <!-- <input class="form-control" type="text" aria-label="default input example" required> -->
                    {{form.nomor_hp}}
                </div>

            </div>

            <input class="btn btn-primary mb-5" type="submit" value="DAFTAR">
        </form>

    </div>
{% endblock %}

pengguna/templates/profil_pengguna.html
{% extends "base.html" %}
{% load static %}

{% block title %}PROFIL PENGGUNA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Profil Pengguna: {{ request.session.nama }}</h1>
    </div>
    
    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url '' %}" method="POST">
            {% csrf_token %}

            <div class="form-group row">

                <h4>Email:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ user.0 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Nama:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ user.2 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Nomor HP:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ user.3 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Alamat:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ user.4 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Nama Bank:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ user.7 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>No. Rekening:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ user.6 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <!-- Peran : Individu atau Organisasi -->
                <h4>Jenis:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ role }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <div>
                    { % if request.session.role == 'ORGANISASI' % }
                        <h4>Nama Organisasi:</h4>
                        <div class="input-group mb-4">
                            <input class="form-control" type="text" value="{{ role.2 }}" aria-label="Disabled input example" disabled readonly>
                        </div>

                        <h4>Nomor Akta Pendirian:</h4>
                        <div class="input-group mb-4">
                            <input class="form-control" type="text" value="{{ role.1 }}" aria-label="Disabled input example" disabled readonly>
                        </div>

                        <h4>No. Telepon Organisasi:</h4>
                        <div class="input-group mb-4">
                            <input class="form-control" type="text" value="{{ role.3 }}" aria-label="Disabled input example" disabled readonly>
                        </div>

                        <h4>Tahun Berdiri:</h4>
                        <div class="input-group mb-4">
                            <input class="form-control" type="text" value="2006" aria-label="{{ role.4 }}" disabled readonly>
                        </div>

                        <h4>Foto Akta Pendirian:</h4>
                        <div class="input-group mb-4">
                            <input class="form-control" type="text" value="Akta.jpg" aria-label="Disabled input example" disabled readonly>
                        </div>
                    { % end if % }
                </div>


<!--                Jenis Individu -->
            <div>
                { % if request.session.role == 'INDIVIDU' % }
                <h4>NIK:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ role.1 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Tanggal Lahir:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ role.2 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Jenis Kelamin:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{ role.3 }}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Foto KTP:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="FotoKTP.jpg" aria-label="Disabled input example" disabled readonly>
                </div>
                { % end if % }
            </div>

<!--        Semua Jenis -->

            <h4>Saldo Donapay:</h4>
            <div class="input-group mb-4">
                <input class="form-control" type="text" value="{{ user.5 }}" aria-label="Disabled input example" disabled readonly>
            </div>
            
            <div>
                <h5>Wishlist Donasi:</h5>

                <div class="container d-flex justify-content-center" align="center">
                    <table class="table table-bordered table-responsive-xl" align="center">
                        <thead class="thead-light">
                            <th><center>ID</center></th>
                            <th><center>Judul</center></th>
                            <th><center>Kategori</center></th>
                            <th><center>Action</center></th>
            
                        </thead>
                            { % for data in data_pd_donasi % }
                            <tr>
                                <td>{{ data.0 }}</td>
                                <td>{{ data.1 }}</td>
                                <td>{{ data.17 }}</td>
                                <td>
                                    <form action="{% url 'trigger_dua:read_pdd' %}" method="get">
                                        <input type="hidden" id="id_u" name="id_u">
                                        <input type="submit" class="btn btn-success btn-sm" value="Detail">
                                    </form>
                
                                    <form action="{% url 'trigger_empat:form_donasi' %}" method="get">
                                        <input type="hidden" id="id_d" name="id_d" value="{{ data.id }}">
                                        <input type="submit" class="btn btn-danger btn-sm" value="Donasi">
                                    </form>

                                    <form action="" method="get">
                                        <input type="hidden" id="id_c" name="id_c" value="{{ data.id }}">
                                        <input type="submit" class="btn btn-warning btn-sm" value="Delete">
                                    </form>
                                </td>
                                </tr>
            
                            <!-- skenario update 
                            <tr>
                                <td>R-001</td>
                                <td>Bangun masjid untuk Desa Maju</td> 
                                <td>Rumah Ibadah</td>
                                    if belum terverifikasi nanti ada tombol "verifikasi" 
                                <td>
                                    detail
                                    <form action="{% url 'trigger_tiga:detail2-daftar-penggalangan-dana' %}" method="get">
                                        <input type="hidden" id="id_u" name="id_u">
                                        <input type="submit" class="btn btn-success btn-sm" value="Detail">
                                    </form>
                                    <form action="{% url 'trigger_empat:form_donasi' %}" method="get">
                                        <input type="hidden" id="id_d" name="id_d">
                                        <input type="submit" class="btn btn-danger btn-sm" value="Donasi">
                                    </form>
                
                                    <form action="" method="get">
                                        <input type="hidden" id="id_c" name="id_c">
                                        <input type="submit" class="btn btn-warning btn-sm" value="Delete">
                                    </form>
                                </td>
                                </tr>
                            -->
                            {% endfor %}
                    </table>
            
                </div>
            
                <div class="container justify-content text-left mb-5">
                    <h6><strong>Jumlah Wishlist: {{ role.jumlah_wishlist }}</strong></h6>
                </div>
            </div>

            <input class="btn btn-danger mb-5" type="submit" value="Cancel">
            <br>
        </form>

    </div>
{% endblock %}

pengguna/templates/read_daftar_pengguna_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}DAFTAR PENGGUNA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Daftar Pengguna</h1>
        <h3>BisaBersama</h3>
    </div>


    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-bordered table-responsive-xl" align="center">
            <thead class="thead-light">
                <th><center>Email</center></th>
                <th><center>Nama</center></th>
                <th><center>Jenis</center></th>
                <th><center>Status</center></th>
                <th><center>Action</center></th>

            </thead>
                {% for d in data %}
                <tr>
                    <td>{{ d.0 }}</td>
                    <td>{{ d.2 }}</td>
                    <td><center>{{ d.14 }}</center></td>
                    <td><center>{{ d.11 }}</center></td>

                    <td>
                        <!-- detail button -->
                        <center>
                        <!-- detail disini bakalan ke profil2 pengguna sesuai dengan pengguna nya
                        tergantung sama d.email nya
                    -->
                        <form action="{% url 'pengguna:profil-pengguna' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u">
                            <input type="submit" class="btn btn-success btn-sm" value="Detail">
                        </form>
                        </center>
                        <!-- verifikasi button -->
                        {% if d.11=='NOT VERIFIED' %}
                            <center>
                                <!-- actionnya mengubah status verifikasi pengguna tersebut menjadi verified 
                                dikembalikan lagi ke html ini-->
                                <form action="{% url 'pengguna:read-daftar-pengguna-admin' %}" method="get">
                                    <input type="hidden" id="id_u" name="id_u" value="{{ d.email }}">
                                    <input type="submit" class="btn btn-primary btn-sm" value="Verifikasi">
                                </form>
                            </center>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            <!-- <tr>
                <tr>
                    <td>rhandrock1z@sciencedaily.com</td>
                    <td>Wuckert Group</td>
                    <td><center>Organisasi</center></td>
                    <td><center>Belum Terverifikasi</center></td>
    
                    <td>
                        <center>
                        detail 
                        <form action="{% url 'pengguna:profil-pengguna-organisasi-adminview' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u">
                            <input type="submit" class="btn btn-success btn-sm" value="Detail">
                        </form>
                        </center>
                        <center>
                        <form action="{% url 'pengguna:daftar-pengguna-admin-afterverif' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u">
                            <input type="submit" class="btn btn-primary btn-sm" value="Verifikasi">
                        </form>
                        </center>
                    </td>
                    </tr> -->
        </table>
    </div>
{% endblock %}