bisasesama/urls.py
from django.contrib import admin
from django.urls import path, include
import beranda.urls as beranda

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('trigger_dua/', include('trigger_dua.urls', namespace='trigger_dua')),
    path('trigger_tiga/', include('trigger_tiga.urls', namespace='trigger_tiga')),
    path('pengguna/', include('pengguna.urls', namespace='pengguna')),
    path('trigger_empat/', include('trigger_empat.urls', namespace='trigger_empat')),
    path('login/', include('login.urls', namespace='login')),
    path('trigger_lima/', include('trigger_lima.urls', namespace='trigger_lima')),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = [
    path("", login, name="login"),
    path("logout/", logout, name="logout"),

]
    # path("form_donasi/", form_donasi, name="form_donasi"),
    # path("donasi/read_donasi", read_donasi, name="read_donasi"),
    # path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),

trigger_dua/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_dua'

urlpatterns = [
    path("form_kategori/", form_kategori, name="form_kategori"),
    path("form_kategori/create_pasien", form_pasien, name="form_pasien"),
    path("form_kategori/cek_pasien", cek_pasien, name="cek_pasien"),
    path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),
    path("penggalangan_dana/detail", read_pdd, name="read_pdd"),
    path("penggalangan_dana/create", form_penggalangan_dana, name="create_pdd"),
    path("penggalangan_dana/delete/", delete_penggalangan_dana, name="delete_pdd"),
    path("penggalangan_dana/cairkan", cairkan_pdd, name="cairkan_pdd"),
    path("komorbid/create/", create_komorbid, name="create_komorbid"),
    path("komorbid/update/(?P<id>[^/]+)$/(?P<penyakit>[^/]+)$/", update_komorbid, name="update_komorbid"),
    path("komorbid/delete/(?P<id>[^/]+)$/(?P<komorbid>[^/]+)$/", delete_komorbid, name="delete_komorbid"),
    path("komorbid/", read_komorbid, name="read_komorbid"),
]

trigger_lima/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_lima'

urlpatterns = [
    path('form_pencairan_dana/', form_pencairan_dana, name='form_pencairan_dana'),
]

trigger_tiga/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_tiga'

urlpatterns = [
    path("daftar-penggalangan-dana-admin", read_daftar_penggalangan_dana_admin, name="daftar-penggalangan-dana-admin"),
    path("daftar-afterverif-penggalangan-dana-admin", read_afterverif_penggalangan_dana_admin, name="daftar-afterverif-penggalangan-dana-admin"),
    path("detail1-daftar-penggalangan-dana", detail1_daftar_penggalangan_dana, name="detail1-daftar-penggalangan-dana"),
    path("detail2-daftar-penggalangan-dana", detail2_daftar_penggalangan_dana, name="detail2-daftar-penggalangan-dana"),
    path("update-penggalangan-dana", form_update_penggalangan_dana, name="form-update-penggalangan-dana"),
    path("form-verifikasi-penggalangan-dana", form_verifikasi_penggalangan_dana, name="form-verifikasi-penggalangan-dana"),
    path("read-kategori-penggalangan-dana-admin", read_kategori_penggalangan_dana_admin, name="read-kategori-penggalangan-dana-admin"),
    path("form-create-kategori-penggalangan-dana", form_create_kategori_penggalangan_dana, name="form-create-kategori-penggalangan-dana"),
    path("form-update-kategori-penggalangan-dana", form_update_kategori_penggalangan_dana, name="form-update-kategori-penggalangan-dana"),

]

trigger_dua/views.py
from django.shortcuts import render, redirect
from django.db import connection, transaction, IntegrityError
from .forms import *
from django.contrib import messages
import random

def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        email = request.session.get('email')
        if email is None:
            return redirect('/login/')
        else:
            return function(request, *args, **kwargs)
    return wrapper

def cursor_fetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

@user_login_required
def create_penggalangan_dana(request):
    if request.session.get("role") != "PENGGALANG_DANA":
        return redirect('/trigger_dua/penggalangan_dana/')
    if request.method == 'POST':
        form = PilihKategoriForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/trigger_dua/penggalangan_dana/")
    if request.method == 'GET':
        form = PilihKategoriForm()
    context = {'form': form}
    return render(request, 'create_kategori_penggalangan_dana.html', context)

@user_login_required
def form_kategori(request):
    context = {}
    context['kategori'] = []
    with connection.cursor() as cursor:
        cursor.execute("set search_path to tk_sidona")
        cursor.execute("SELECT * from KATEGORI_PD")

        kategori = cursor.fetchall()
        for i in range(len(kategori)):
            context["kategori"].append([
                kategori[i][0], kategori[i][1]
            ])

        cursor.execute("set search_path to public")
    if request.method == 'post':
        kategori_simpan = request.POST["kategori"]
        request.session["kategori"] = kategori_simpan
        print(request.session["kategori"])

    return render(request, 'create_kategori_penggalangan_dana.html', context)

@user_login_required
def form_pasien(request):
    if request.session.get("role") != "PENGGALANG_DANA":
        return redirect('/')
    if request.method == 'POST':
        with connection.cursor() as cursor:
            nik = request.POST["nik"]
            nama = request.POST["nama"]
            tanggal_lahir = request.POST["tanggal_lahir"]
            alamat = request.POST["alamat"]
            pekerjaan = request.POST["pekerjaan"]
            cursor.execute('set search_path to tk_sidona')
            try:
                cursor.execute("INSERT INTO PASIEN VALUES(%s, %s, %s, %s, %s)",
                           [nik, nama, tanggal_lahir, alamat, pekerjaan])
                cursor.execute("set search_path to public")
                request.session["nik"] = cek_pasien
                return redirect("/trigger_dua/penggalangan_dana/create")
            except:
                messages.add_message(request, messages.WARNING,
                                     f"Maaf, ID Pasien sudah ada!")
    return render(request, 'create_form_pasien.html')

@user_login_required
def cek_pasien(request):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            cek_pasien = request.POST["cek_pasien"]
            cursor.execute("set search_path to tk_sidona")
            cursor.execute("SELECT * from PASIEN WHERE nik = %s ", [cek_pasien])
            pasien = cursor.fetchall()
            cursor.execute("set search_path to public")
            if pasien == []:
                messages.add_message(request, messages.WARNING,
                                     f"Maaf, Pasien tidak ditemukan. Mohon coba lagi!")
            else:
                request.session["nik"] = cek_pasien
                return redirect("/trigger_dua/penggalangan_dana/create")

    return render(request, 'cek_pasien_terdaftar.html')

@user_login_required
def form_rumah_ibadah(request):
    if request.session.get("role") != "PENGGALANG_DANA":
        return redirect('/')
    if request.method == 'POST':
        with connection.cursor() as cursor:
            no_sertif = request.POST["no_sertif"]
            nama = request.POST["nama"]
            alamat = request.POST["alamat"]
            jenis = request.POST["jenis"]
            cursor.execute('set search_path to tk_sidona')
            try:
                cursor.execute("INSERT INTO RUMAH_IBADAH VALUES(%s, %s, %s, %s)",
                           [no_sertif, nama, alamat, jenis])
                cursor.execute("set search_path to public")
                request.session["nosertifikat"] = no_sertif
                return redirect("/trigger_dua/penggalangan_dana/create")
            except:
                messages.add_message(request, messages.WARNING,
                                     f"Maaf, Rumah Ibadah sudah ada!")
    return render(request, 'create_form_rumah_ibadah.html')

@user_login_required
def cek_rumah_ibadah(request):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            cek_rumah_ibadah = request.POST["cek_rumah_ibadah"]
            cursor.execute("set search_path to tk_sidona")
            cursor.execute("SELECT * from RUMAH_IBADAH WHERE nosertifikat = %s ", [cek_rumah_ibadah])
            rumah_ibadah = cursor.fetchall()
            if rumah_ibadah == []:
                messages.add_message(request, messages.WARNING,
                                     f"Maaf, Rumah Ibadah tidak ditemukan. Mohon coba lagi!")
            else:
                request.session["nosertifikat"] = cek_rumah_ibadah
                return redirect("/trigger_dua/penggalangan_dana/create")

            cursor.execute("set search_path to public")
    return render(request, 'cek_rumah_ibadah_terdaftar.html')

@user_login_required
def form_penggalangan_dana(request):
    # context = {}
    # nik = request.session["nik"]
    # with connection.cursor() as cursor:
    #     cursor.execute("set search_path to tk_sidona")
    #     cursor.execute("SELECT * from PASIEN WHERE nik = %s ", [nik])
    #     pasien = cursor.fetchall()
    #     print(pasien)
    #     context["pasien"] = pasien[0]
    #
    #     cursor.execute("select id from penggalangan_dana_pd")
    #     id = cursor.fetchall()
    #
    #     id_baru = random.randint(100000000, 999999999)
    #     while (id_baru in id):
    #         id_baru = random.randint(100000000, 999999999)
    #
    #     context["id"] = id_baru
    return render(request, 'create_form_penggalangan_dana.html')

@user_login_required
def read_penggunaan_dana(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT timestamp, nominal, deskripsi "
                       "FROM RIWAYAT_PENGGUNAAN_DANA "
                       "WHERE idpd = % s, timestamp = % s;", request.GET.get('id_pd'), request.get('timestamp'))
        data_pdd = cursor_fetchall(cursor)

        context = {'data': data_pdd}
    return render(request, 'read_penggalangan_dana_pribadi.html', context)

@user_login_required
def read_pdd_pribadi(request):
    penggalangan_dana = 0
    penggalangan_dana_aktif = 0
    with connection.cursor() as cursor:
        cursor.execute('set search_path to public')
        email = request.session["email"]
        cursor.execute('set search_path to tk_sidona')
        print(email)
        cursor.execute("SELECT PDD.id, PDD.judul, PDD.kota, PDD.provinsi, PDD.tanggal_aktif_awal, PDD.tanggal_aktif_akhir, PDD.sisa_hari, "
                       "PDD.jumlah_dibutuhkan, KPD.nama_kategori, PDD.status_verifikasi "
                       "FROM penggalangan_dana_pd AS PDD, kategori_pd AS KPD "
                       "WHERE PDD.id_kategori = KPD.id AND PDD.email_user = %s "
                       "ORDER BY PDD.id;", [email])
        data_pdd = cursor_fetchall(cursor)
        print(data_pdd)

        penggalangan_dana = len(data_pdd)

        for i in range(len(data_pdd)):
            if data_pdd[i]["status_verifikasi"] == "Terverifikasi":
                penggalangan_dana_aktif += 1

    context = {'data': data_pdd, 'pdd': penggalangan_dana, 'aktif': penggalangan_dana_aktif}
    return render(request, 'read_penggalangan_dana_pribadi.html', context)

@user_login_required
def read_donatur(request):
    with connection.cursor() as cursor:

        cursor.execute("SELECT email, timestamp, nominal, doa"
                       "FROM DONASI"
                       "WHERE idpd = %s, timestamp = %s;", request.GET.get('id_pd'), request.get('timestamp'))
        data_pdd = cursor_fetchall(cursor)

    context = {'data': data_pdd}
    return render(request, 'read_penggalangan_dana_pribadi.html', context)

@user_login_required
def read_pdd(request):

    return render(request, 'read_penggalangan_dana.html')

@user_login_required
def delete_penggalangan_dana(request):
    if request.session.get("role") != "PENGGALANG_DANA":
        return redirect('/trigger_dua/penggalangan_dana/')
    if request.method == 'GET':
        # if request.GET.get('id') is None:
        #     return redirect('/trigger_dua/penggalangan_dana/')
        # else:
        #     id = request.GET.get('id')
        try:
            with connection.cursor() as cursor:
                # with transaction.atomic():
                cursor.execute("""\
                DELETE FROM penggalangan_dana_pd WHERE id=%s\
                """, [id])
        except IntegrityError:
            pass
        return redirect('/trigger_dua/penggalangan_dana/')

@user_login_required
def cairkan_pdd(request):
    return render(request, 'read_penggalangan_dana_pribadi.html')

def read_komorbid(request):
    with connection.cursor() as cursor:
        if request.session.get("role") == "PENGGALANG_DANA":
            cursor.execute('set search_path to public')
            email = request.session["email"]

            cursor.execute('set search_path to tk_sidona')

            cursor.execute("SELECT PDD.id, PDD.judul, PDK.penyakit, K.komorbid "
                           "FROM penggalangan_dana_pd AS PDD, pd_kesehatan as PDK, komorbid AS K "

trigger_dua/templates/cek_pasien_terdaftar.html
{% extends "base.html" %}
{% load static %}

{% block title %}CEK PASIEN{% endblock %}

{% block content %}
      <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Cek Pasien yang Terdaftar</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:cek_pasien' %}" method="post">
            {% csrf_token %}

            <h4>NIK Pasien:</h4>
            <div class="input-group mb-3">
                <input class="form-control" type="text" aria-label="default input example" name="cek_pasien" value="{{request.POST.cek_pasien}}" required>
            </div>
            <br>

            <input class="btn btn-primary mb-5" type="submit" value="CHECK">
        </form>
    </div>
{% endblock %}

trigger_dua/templates/cek_rumah_ibadah_terdaftar.html
{% extends "base.html" %}
{% load static %}

{% block title %}CEK RUMAH IBADAH{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Cek Rumah Ibadah yang Terdaftar</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:cek_rumah_ibadah' %}" method="post">
            {% csrf_token %}
            <h4>Nomor Sertifikat Rumah Ibadah:</h4>
            <div class="input-group mb-3">
                <input class="form-control" type="text" aria-label="default input example" name="cek_rumah_ibadah" value="{{request.POST.cek_rumah_ibadah}}" required>
            </div>
            <br>

            <input class="btn btn-primary mb-5" type="submit" value="CHECK">
        </form>
    </div>
{% endblock %}

trigger_dua/templates/create_form_pasien.html
{% extends "base.html" %}
{% load static %}

{% block title %}FORM PASIEN{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Form Pasien</h1>
        <hr>
        <h4>Identitas Pasien</h4>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:form_pasien' %}" method="POST">
            {% csrf_token %}

            <div class="form-group row">

                <h4>NIK:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example"  name="nik" value="{{request.POST.nik}}" required>
                </div>

                <h4>Nama: </h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example"  name="nama" value="{{request.POST.nama}}" required>
                </div>

                <h4>Tanggal Lahir:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example"  name="tanggal_lahir" value="{{request.POST.tanggal_lahir}}" required>
                </div>

                <h4>Alamat:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" name="alamat" value="{{request.POST.alamat}}" required>
                </div>

                <h4>Pekerjaan:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" name="pekerjaan" value="{{request.POST.pekerjaan}}" required>
                </div>

            </div>

            <input class="btn btn-primary mb-5" type="submit" value="NEXT">
        </form>

    </div>
{% endblock %}

trigger_dua/templates/create_form_penggalangan_dana.html
{% extends "base.html" %}
{% load static %}

{% block title %}FORM PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Form Penggalangan Dana</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:read_pdd' %}" method="POST">

            <h3 style="text-align: center; margin-bottom: 40px">Informasi Umum Penggalangan Dana</h3>
            {% csrf_token %}

            <div class="form-group row">

                <h4>ID Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{id.0}}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Email Penggalang Dana: </h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{request.session.email}}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Judul:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>

                <h4>Deskripsi:</h4>
                <div class="input-group mb-4">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
                </div>

                <h4>Kota:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>

                <h4>Provinsi:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>

                <h4>Deadline Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>

                <h4>Jumlah Target Dana (Rupiah):</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>

            </div>

            <h3 style="text-align: center; margin-bottom: 40px; margin-top:25px">Informasi Tambahan Penggalangan Dana</h3>

            <div class="form-group row">

                <h4>Kategori:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Kesehatan" aria-label="Disabled input example" disabled readonly>
                </div>

<!--                Kategori kesehatan-->

                <h4>NIK Pasien:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{pasien.0}}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Nama Pasien:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="{{pasien.1}}" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Penyakit Utama:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>

<!--                Kategori Rumah Ibadah-->
                <h4>Nomor Sertifikat Rumah Ibadah:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="RI-01" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Kategori Aktivitas:</h4>
                <select id="kategori" class="form-control mb-4" aria-label="Default select example" required>
                  <option selected>Pilih ID Penggalangan Dana</option>
                  <option value="1">Belajar</option>
                  <option value="2">Menyapu</option>
                  <option value="3">Mengepel</option>
                  <option value="4">Berdoa</option>
                  <option value="5">Bersih-bersih</option>
                </select>

<!--                Semua kategori -->
                <h4>Berkas Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" required>
                </div>
            </div>

            <input class="btn btn-primary mb-5" type="submit" value="CREATE">
            <br>
        </form>

    </div>
{% endblock %}

trigger_dua/templates/create_form_rumah_ibadah.html
{% extends "base.html" %}
{% load static %}

{% block title %}FORM RUMAH IBADAH{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Form Rumah Ibadah</h1>
        <hr>
        <h4>Informasi Rumah Ibadah</h4>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:form_rumah_ibadah' %}" method="POST">
            {% csrf_token %}

            <div class="form-group row">

                <h4>Nomor Sertifikat:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" name="no_sertif" value="{{request.POST.no_sertif}}"  required>
                </div>

                <h4>Nama: </h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" name="nama" value="{{request.POST.nama}}" required>
                </div>

                <h4>Alamat:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" name="alamat" value="{{request.POST.alamat}}" required>
                </div>

                <h4>Jenis:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" name="jenis" value="{{request.POST.jenis}}"  required>
                </div>

            </div>

            <input class="btn btn-primary mb-5" type="submit" value="NEXT">
        </form>

    </div>
{% endblock %}

trigger_dua/templates/create_komorbid.html
{% extends "base.html" %}
{% load static %}

{% block title %}CREATE KOMORBID{% endblock %}

{% block content %}
      <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Form Penyakit Komorbid</h1>
        <h3>Informasi Penyakit Komorbid</h3>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:create_komorbid' %}" method="POST">
            {% csrf_token %}
            <h4>ID Penggalangan Dana:</h4>
            <select id="pdk" name="pdk" value="{{request.POST.pdk}}" class="form-control" required>
                <option value="" selected>Pilih ID Penggalangan Dana</option>
                {% for idpd in pdk %}
                <option value={{idpd.0}}>{{idpd.0}}</option>
                {% endfor %}
            </select>

            <br>
            <br>

            <h4>Komorbid:</h4>
            <div class="input-group mb-3">
                <input class="form-control" type="text" aria-label="default input example" name="komorbid" value="{{request.POST.komorbid}}" required>
            </div>
            <br>
            <input class="btn btn-primary mb-5" type="submit" value="CREATE">
        </form>
    </div>
{% endblock %}

trigger_dua/templates/read_komorbid.html
{% extends "base.html" %}
{% load static %}

{% block title %}KOMORBID{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Halaman Kelola Penyakit Komorbid</h1>
        <h3>BisaBersama</h3>
    </div>

    {% if request.session.role == 'PENGGALANG_DANA' %}
    <div class="container justify-content text-right mb-4">
        <a href="./create/" class="btn btn-primary btn active" role="button" aria-pressed="true">Tambah Penyakit Komorbid Baru</a>
    </div>
    {% endif %}

    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-bordered table-responsive-xl" align="center">
            <thead class="thead-light">
                <th><center>ID</center></th>
                <th><center>Judul</center></th>
                <th><center>Penyakit Utama</center></th>
                <th><center>Penyakit Komorbid</center></th>
                {% if request.session.role == 'PENGGALANG_DANA' %}
                <th><center>Action</center></th>
                {% endif %}
            </thead>
            {% for row in data %}
                <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.judul }}</td>
                <td>{{ row.penyakit }}</td>
                <td>{{ row.komorbid }}</td>
                    {% if request.session.role == 'PENGGALANG_DANA' %}
                <td>
                    <form action="{% url 'trigger_dua:update_komorbid' row.id row.penyakit %}" method="get">
                        <input type="hidden" id="id_u" name="id_u">
                        <input type="submit" class="btn btn-success btn-sm" value="Update">
                    </form>

                    <form action="{% url 'trigger_dua:delete_komorbid' row.id row.komorbid %}" method="get">
                        <input type="hidden" id="id_d" name="id_d">
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>
                </td>
                {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

trigger_dua/templates/read_penggalangan_dana_pribadi.html
{% extends "base.html" %}
{% load static %}

{% block title %}DAFTAR PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Halaman Daftar Penggalangan Dana Pribadi</h1>
        <h3>BisaBersama</h3>
    </div>


    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-bordered table-responsive-xl" align="center">
            <thead class="thead-light">
                <th><center>ID</center></th>
                <th><center>Judul</center></th>
                <th><center>Kota</center></th>
                <th><center>Prov</center></th>
                <th><center>Tanggal Aktif Awal</center></th>
                <th><center>Deadline</center></th>
                <th><center>Sisa Hari</center></th>
                <th><center>Target Dana</center></th>
                <th><center>Kategori</center></th>
                <th><center>Status Verifikasi</center></th>
                {% if request.session.role == 'PENGGALANG_DANA' %}
                <th><center>Action</center></th>
                {% endif %}

            </thead>
                <tr>
                {% for row in data %}
                <td>{{ row.id }} </td>
                <td>{{ row.judul }}</td>
                <td>{{ row.kota }}</td>
                <td>{{ row.provinsi }}</td>
                <td>{{ row.tanggal_aktif_awal }}</td>
                <td>{{ row.tanggal_aktif_akhir }}</td>
                <td>{{ row.sisa_hari }}</td>
                <td>{{ row.jumlah_dibutuhkan }}</td>
                <td>{{ row.nama_kategori }}</td>
                <td>{{ row.status_verifikasi }}</td>
                <td>
                    <form action="{% url 'trigger_dua:read_pdd' %}" method="get">
                        <input type="hidden" id="id_u" name="id_u">
                        <input type="submit" class="btn btn-success btn-sm" value="Detail">
                    </form>

                    {% if row.status_verifikasi == 'Belum verifikasi' %}
                    <form action="{% url 'trigger_dua:delete_pdd' %}" method="get">
                        <input type="hidden" id="id_d" name="id_d">
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>
                    {% endif %}

                    <form action="{% url 'trigger_lima:form_pencairan_dana' %}" method="get">
                        <input type="hidden" id="id_c" name="id_c">
                        <input type="submit" class="btn btn-warning btn-sm" value="Cairkan">
                    </form>

<!--                    <form action="{% url 'trigger_tiga:form-update-penggalangan-dana' %}" method="get">-->
<!--                        <input type="hidden" id="id_c" name="id_c">-->
<!--                        <input type="submit" class="btn btn-primary btn-sm" value="Update">-->
<!--                    </form>-->
                </td>

                </tr>
            {% endfor %}

        </table>

    </div>

    <div class="container justify-content text-left mb-5">
        <h6><strong>Jumlah Penggalangan Dana: {{ pdd }}</strong></h6>
        <h6><strong>Jumlah Penggalangan Dana Aktif: {{ aktif }}</strong></h6>
    </div>

{% endblock %}