bisasesama/urls.py
from django.contrib import admin
from django.urls import path, include
import beranda.urls as beranda

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('trigger_dua/', include('trigger_dua.urls', namespace='trigger_dua')),
    path('trigger_tiga/', include('trigger_tiga.urls', namespace='trigger_tiga')),
    path('pengguna/', include('pengguna.urls', namespace='pengguna')),
    path('trigger_empat/', include('trigger_empat.urls', namespace='trigger_empat')),
    path('login/', include('login.urls', namespace='login')),
    path('trigger_lima/', include('trigger_lima.urls', namespace='trigger_lima')),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = [
    path("", login, name="login"),
    path("logout/", logout, name="logout"),

]
    # path("form_donasi/", form_donasi, name="form_donasi"),
    # path("donasi/read_donasi", read_donasi, name="read_donasi"),
    # path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),

trigger_dua/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_dua'

urlpatterns = [
    path("form_kategori/", form_kategori, name="form_kategori"),
    path("form_kategori/create_pasien", form_pasien, name="form_pasien"),
    path("form_kategori/cek_pasien", cek_pasien, name="cek_pasien"),
    path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),
    path("penggalangan_dana/detail", read_pdd, name="read_pdd"),
    path("penggalangan_dana/create", form_penggalangan_dana, name="create_pdd"),
    path("penggalangan_dana/delete/", delete_penggalangan_dana, name="delete_pdd"),
    path("penggalangan_dana/cairkan", cairkan_pdd, name="cairkan_pdd"),
    path("komorbid/create/", create_komorbid, name="create_komorbid"),
    path("komorbid/update/(?P<id>[^/]+)$/(?P<penyakit>[^/]+)$/", update_komorbid, name="update_komorbid"),
    path("komorbid/delete/(?P<id>[^/]+)$/(?P<komorbid>[^/]+)$/", delete_komorbid, name="delete_komorbid"),
    path("komorbid/", read_komorbid, name="read_komorbid"),
]

trigger_empat/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_empat'

urlpatterns = [
    path("penggalangan_dana_POV_Pengguna/", cek_penggalangan_dana, name="read_halaman_penggalangan_dana"),
    path("form_donasi/", form_donasi, name="form_donasi"),
    path("donasi/read_donasi", read_donasi, name="read_donasi"),
    path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),
    path('tambah_Wishlist',tambah_wishlist, name= 'tambah_wishlist'),
    path('delete_wishlist', delete_wishlist_donasi, name = 'delete_wishlist' ),
    # path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    # path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    # path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),  
]

trigger_tiga/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_tiga'

urlpatterns = [
    path("daftar-penggalangan-dana-admin", read_daftar_penggalangan_dana_admin, name="daftar-penggalangan-dana-admin"),
    path("daftar-afterverif-penggalangan-dana-admin", read_afterverif_penggalangan_dana_admin, name="daftar-afterverif-penggalangan-dana-admin"),
    path("detail1-daftar-penggalangan-dana", detail1_daftar_penggalangan_dana, name="detail1-daftar-penggalangan-dana"),
    path("detail2-daftar-penggalangan-dana", detail2_daftar_penggalangan_dana, name="detail2-daftar-penggalangan-dana"),
    path("update-penggalangan-dana", form_update_penggalangan_dana, name="form-update-penggalangan-dana"),
    path("form-verifikasi-penggalangan-dana", form_verifikasi_penggalangan_dana, name="form-verifikasi-penggalangan-dana"),
    path("read-kategori-penggalangan-dana-admin", read_kategori_penggalangan_dana_admin, name="read-kategori-penggalangan-dana-admin"),
    path("form-create-kategori-penggalangan-dana", form_create_kategori_penggalangan_dana, name="form-create-kategori-penggalangan-dana"),
    path("form-update-kategori-penggalangan-dana", form_update_kategori_penggalangan_dana, name="form-update-kategori-penggalangan-dana"),

]

trigger_tiga/views.py
from django.db import connection
from django.shortcuts import render

from pengguna.views import admin

# with connection.cursor() as cursor:
#         cursor.execute(
#             """
#             SET SEARCH_PATH TO TK_SIDONA;
#             """
#         )

@admin
def read_daftar_penggalangan_dana_admin(request):
    context = {}
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT * FROM PENGGALANGAN_DANA_PD;
            """
        )
        
        data = cursor.fetchall()
        print(data)

        context['data_pd'] = data
    return render(request, 'read_daftar_penggalangan_dana_admin.html', context)

def read_afterverif_penggalangan_dana_admin(request):
    return render(request, 'read_afterverif_daftar_penggalangan_dana_admin.html')

def detail1_daftar_penggalangan_dana(request):
    return render(request, 'detail1_daftar_penggalangan_dana_admin.html')

def detail2_daftar_penggalangan_dana(request):
    return render(request, 'detail2_daftar_penggalangan_dana_admin.html')

# POV Pengguna
def form_update_penggalangan_dana(request):
    id_verifikasi=request.session.get("verifikasi_id")
    return render(request, 'form_update_penggalangan_dana.html')

# Catatan pengajuan
# Hanya boleh dilakukan admin
def form_verifikasi_penggalangan_dana(request):
    return render(request, 'form_verifikasi_penggalangan_dana.html')

# Halaman kategori penggalangan dana
# Hanya dapat diakses oleh admin => Soalnya ada Update button nya
def read_kategori_penggalangan_dana_admin(request):
    return render(request, 'read_kategori_penggalangan_dana_admin.html')

def form_create_kategori_penggalangan_dana(request):
    return render(request, 'form_create_kategori_penggalangan_dana.html')

def form_update_kategori_penggalangan_dana(request):
    return render(request, 'form_update_kategori_penggalangan_dana.html')

trigger_tiga/templates/detail1_daftar_penggalangan_dana_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}DETAIL PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Detail Penggalangan Dana: nama_PD</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:read_pdd' %}" method="POST">

            <h3 style="text-align: center; margin-bottom: 40px">Informasi Umum Penggalangan Dana</h3>
            {% csrf_token %}

            <div class="form-group row">

                <h4>ID Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="K-001" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Email Penggalang Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="hbavidge0@squidoo.com" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Judul:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Ayo bantu Zulfahri menghadapi penyakit Demam Berdarahnya!" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Deskripsi:</h4>
                <div class="input-group mb-4">
                    <textarea class="form-control" aria-label="Disabled input example" id="exampleFormControlTextarea1" rows="3" disabled readonly>Action|Adventure|Fantasy</textarea>
                </div>

                <h4>Kota:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Bandung" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Provinsi:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Jawa Barat" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Deadline Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="7 Desember 2021" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Jumlah Target Dana (Rupiah):</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rp 1.000.000,-" aria-label="Disabled input example" disabled readonly>
                </div>
            </div>

            <h3 style="text-align: center; margin-bottom: 40px; margin-top:25px">Informasi Tambahan Penggalangan Dana</h3>

            <div class="form-group row">

                <h4>Kategori:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Kesehatan" aria-label="Disabled input example" disabled readonly>
                </div>

<!--                Kategori kesehatan-->

                <h4>NIK Pasien:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="320107473" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Nama Pasien:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Zulfahri" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Penyakit Utama:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Covid" aria-label="Disabled input example" disabled readonly>
                </div>

<!--                Kategori Rumah Ibadah
                <h4>Nomor Sertifikat Rumah Ibadah:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="RI-01" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Kategori Aktivitas:</h4>
                <select id="kategori" class="form-control mb-4" disabled>
                  <option value="1">Belajar</option>
                </select>
            -->

<!--                Semua kategori -->
                <h4>Berkas Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="https://dropbox.com" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Catatan Pengajuan:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Jumlah Terkumpul:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rp 5.000.000,-" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Donatur:</h4>
                <table class="table table-bordered table-responsive-xl" align="center">
                    <thead>
                        <th><center>Email</center></th>
                        <th><center>Timestamp</center></th>
                        <th><center>Nominal</center></th>
                        <th><center>Doa</center></th>
                    </thead>
                        <tr>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        </tr>
                </table>

                <h4>Jumlah Terpakai:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rp 2.000.000,-" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Rincian Penggunaan:</h4>
                <table class="table table-bordered table-responsive-xl" align="center">
                    <thead>
                        <th><center>Waktu</center></th>
                        <th><center>Nominal</center></th>
                        <th><center>Deskripsi</center></th>
                    </thead>
                        <tr>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        </tr>
                </table>



            </div>

            <input class="btn btn-danger mb-5" type="submit" value="Cancel">
            <br>
        </form>

    </div>
{% endblock %}

trigger_tiga/templates/detail2_daftar_penggalangan_dana_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}DETAIL PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Detail Penggalangan Dana: nama_PD</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_dua:read_pdd' %}" method="POST">

            <h3 style="text-align: center; margin-bottom: 40px">Informasi Umum Penggalangan Dana</h3>
            {% csrf_token %}

            <div class="form-group row">

                <h4>ID Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="R-001" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Email Penggalang Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="pwhiskin1@360.com" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Judul:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Bangun masjid untuk Desa Maju" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Deskripsi:</h4>
                <div class="input-group mb-4">
                    <textarea class="form-control" aria-label="Disabled input example" id="exampleFormControlTextarea1" rows="3" disabled readonly>Drama</textarea>
                </div>

                <h4>Kota:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Jakarta" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Provinsi:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="DKI Jakarta" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Deadline Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="10 Desember 2021" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Jumlah Target Dana (Rupiah):</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rp 10.000.000,-" aria-label="Disabled input example" disabled readonly>
                </div>
            </div>

            <h3 style="text-align: center; margin-bottom: 40px; margin-top:25px">Informasi Tambahan Penggalangan Dana</h3>

            <div class="form-group row">

                <h4>Kategori:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rumah Ibadah" aria-label="Disabled input example" disabled readonly>
                </div>

<!--                Kategori kesehatan

                <h4>NIK Pasien:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="320107473" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Nama Pasien:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Zulfahri" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Penyakit Utama:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Covid" aria-label="Disabled input example" disabled readonly>
                </div>
            -->

<!--                Kategori Rumah Ibadah-->
                <h4>Nomor Sertifikat Rumah Ibadah:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="RI-01" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Kategori Aktivitas:</h4>
                <select id="kategori" class="form-control mb-4" disabled>
                  <option value="1">Belajar</option>
                </select>

<!--                Semua kategori -->
                <h4>Berkas Penggalangan Dana:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="https://dropbox.com" aria-label="Disabled input example" disabled readonly>
                </div>

                <!-- diambil dari catatan_pengajuan -->
                <h4>Catatan Pengajuan:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Jumlah Terkumpul:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rp 5.000.000,-" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Donatur:</h4>
                <table class="table table-bordered table-responsive-xl" align="center">
                    <thead>
                        <th><center>Email</center></th>
                        <th><center>Timestamp</center></th>
                        <th><center>Nominal</center></th>
                        <th><center>Doa</center></th>
                    </thead>
                        <tr>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        </tr>
                </table>

                <h4>Jumlah Terpakai:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" value="Rp 2.000.000,-" aria-label="Disabled input example" disabled readonly>
                </div>

                <h4>Rincian Penggunaan:</h4>
                <table class="table table-bordered table-responsive-xl" align="center">
                    <thead>
                        <th><center>Waktu</center></th>
                        <th><center>Nominal</center></th>
                        <th><center>Deskripsi</center></th>
                    </thead>
                        <tr>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        </tr>
                </table>



            </div>

            <input class="btn btn-danger mb-5" type="submit" value="Cancel">
            <br>
        </form>

    </div>
{% endblock %}

trigger_tiga/templates/form_verifikasi_penggalangan_dana.html
{% extends "base.html" %}
{% load static %}

{% block title %}FORM VERIFIKASI PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Form Verifikasi Penggalangan Dana</h1>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'trigger_tiga:daftar-afterverif-penggalangan-dana-admin' %}" method="POST">
            {% csrf_token %}

            <div class="form-group row">

                <h4>Catatan Pengajuan:</h4>
                <div class="input-group mb-4">
                    <input class="form-control" type="text" aria-label="default input example" rows required>
                </div>

            </div>
            
            <input class="btn btn-success mb-5" type="submit" value="VERIFIKASI">
            <a class="btn btn-danger mb-5" href="/trigger_tiga/daftar-penggalangan-dana-admin" role="button">TOLAK VERIFIKASI</a>

            <!-- <input class="btn btn-danger mb-5" type="submit" value="TOLAK VERIFIKASI"> -->

            <!-- <form action="{% url 'trigger_tiga:daftar-penggalangan-dana-admin' %}" method="get">
                <input type="hidden" id="id_u" name="id_u">
                <input type="submit" class="btn btn-warning btn-sm" value="TOLAK VERIFIAKASI">
            </form> -->
        </form>

    </div>
{% endblock %}

trigger_tiga/templates/read_afterverif_daftar_penggalangan_dana_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}DAFTAR PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Halaman Daftar Penggalangan Dana</h1>
        <h1>(POV Admin Sistem)</h1>
        <h3>BisaBersama</h3>
    </div>


    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-bordered table-responsive-xl" align="center">
            <thead class="thead-light">
                <th><center>ID</center></th>
                <th><center>Judul</center></th>
                <th><center>Kota</center></th>
                <th><center>Prov</center></th>
                <th><center>Tanggal Aktif Awal</center></th>
                <th><center>Deadline</center></th>
                <th><center>Sisa Hari</center></th>
                <th><center>Target Dana</center></th>
                <th><center>Kategori</center></th>
                <th><center>Status Verifikasi</center></th>
                <th><center>Action</center></th>

            </thead>
                <tr>
                <td>K-001</td>
                <td>Ayo bantu Zulfahri menghadapi penyakit Demam Berdarahnya!</td>
                <td>Bandung</td>
                <td>Jawa Barat</td>
                <td>15 November 2021</td>
                <td>7 Desember 2021</td>
                <td>20 hari</td>
                <td>Rp 1.000.000,-</td>
                <td>Kesehatan</td>
                <td>Sudah Terverifikasi</td>
                <td>
                    <!-- detail -->
                    <form action="{% url 'trigger_tiga:detail1-daftar-penggalangan-dana' %}" method="get">
                        <input type="hidden" id="id_u" name="id_u">
                        <input type="submit" class="btn btn-success btn-sm" value="Detail">
                    </form>

                    <!-- <form action="{% url 'trigger_dua:delete_pdd' %}" method="get">
                        <input type="hidden" id="id_d" name="id_d">
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>

                    <form action="{% url 'trigger_dua:cairkan_pdd' %}" method="get">
                        <input type="hidden" id="id_c" name="id_c">
                        <input type="submit" class="btn btn-warning btn-sm" value="Cairkan">
                    </form> -->
                </td>
                </tr>
            <tr>
            <td>R-001</td>
            <td>Bangun masjid untuk Desa Maju</td>
            <td>Jakarta</td>
            <td>DKI Jakarta</td>
            <!-- tanggal aktif awal udah ada soalnya udah ke verif -->
            <td>23 November 2021</td> 
            <!-- tanggal aktif awal masih kosong karena blm di verif -->
            <td>10 Desember 2021</td>
            <!-- sisa hari masih kosong karena blm di-verif -->
            <td>17 hari</td>
            <td>Rp 10.000.000,-</td>
            <td>Rumah Ibadah</td>
            <!-- UDAH VERIF -->
            <td>Sudah Terverifikasi</td>
            <td>
                <!-- detail -->
                <form action="{% url 'trigger_tiga:detail2-daftar-penggalangan-dana' %}" method="get">
                    <input type="hidden" id="id_u" name="id_u">
                    <input type="submit" class="btn btn-success btn-sm" value="Detail">
                </form>
                <!-- <form action="{% url 'trigger_tiga:detail2-daftar-penggalangan-dana' %}" method="get">
                    <input type="hidden" id="id_u" name="id_u">
                    <input type="submit" class="btn btn-primary btn-sm" value="Verifikasi">
                </form> -->
            </td>
            </tr>
        </table>
    </div>
{% endblock %}

trigger_tiga/templates/read_daftar_penggalangan_dana_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}DAFTAR PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Halaman Daftar Penggalangan Dana</h1>
        <!-- Admin View -->
        <h3>BisaBersama</h3>
    </div>


    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-bordered table-responsive-xl" align="center">
            <thead class="thead-light">
                <th><center>ID</center></th>
                <th><center>Judul</center></th>
                <th><center>Kota</center></th>
                <th><center>Prov</center></th>
                <th><center>Tanggal Aktif Awal</center></th>
                <th><center>Deadline</center></th>
                <th><center>Sisa Hari</center></th>
                <th><center>Target Dana</center></th>
                <th><center>Kategori</center></th>
                <th><center>Status Verifikasi</center></th>
                <th><center>Action</center></th>

            </thead>
                {% csrf_token %}
                {% for r in data_pd %}
                <tr>
                    <td>{{ r.0 }}</td>
                    <td>{{ r.1 }}</td>
                    <td>{{ r.3 }}</td>
                    <td>{{ r.4 }}</td>
                    <td>{{ r.8 }}</td>
                    <td>{{ r.9 }}</td>
                    <td>{{ r.13 }}</td>
                    <td>{{ r.14 }}</td>
                    <td>{{ r.2 }}</td>
                    <td>{{ r.6 }}</td>
                    <td>
                        <!-- detail -->
                        <form action="{% url 'trigger_tiga:detail1-daftar-penggalangan-dana' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u">
                            <input type="submit" class="btn btn-success btn-sm" value="Detail">
                        </form>

                        {% if r.6 == "Belum verifikasi" %}
                        <form action="{% url 'trigger_tiga:form-verifikasi-penggalangan-dana' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u" value="{{ r.0 }}">
                            <input type="submit" class="btn btn-primary btn-sm" value="Verifikasi">
                        </form>
                        {% endif %}
                        <!-- <form action="{% url 'trigger_dua:delete_pdd' %}" method="get">
                            <input type="hidden" id="id_d" name="id_d">
                            <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                        </form>

                        <form action="{% url 'trigger_dua:cairkan_pdd' %}" method="get">
                            <input type="hidden" id="id_c" name="id_c">
                            <input type="submit" class="btn btn-warning btn-sm" value="Cairkan">
                        </form> -->
                    </td>
                </tr>
        </table>
    </div>
{% endblock %}

trigger_tiga/templates/read_kategori_penggalangan_dana_admin.html
{% extends "base.html" %}
{% load static %}

{% block title %}KATEGORI PENGGALANGAN DANA{% endblock %}

{% block content %}
    <div class='bg-primary jumbotron justify-content-center text-white' align="center">
        <h1>Halaman Kategori Penggalangan Dana</h1>
        <h3>BisaBersama</h3>
    </div>


    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-bordered table-responsive-xl" align="center">
            <thead class="thead-light">
                <th><center>ID</center></th>
                <th><center>Nama Kategori</center></th>
                <th><center>Action</center></th>

            </thead>
                <tr>
                <td><center>1</center></td>
                <td>Kesehatan</td>
                <td>
                    <!-- Lead to update form -->
                    <center>
                    <form action="{% url 'trigger_tiga:form-update-kategori-penggalangan-dana' %}" method="get">
                        <input type="hidden" id="id_u" name="id_u">
                        <input type="submit" class="btn btn-primary btn-sm" value="Update">
                    </form>
                    </center>
                </td>
                </tr>

                <tr>
                    <td><center>2</center></td>
                    <td>Rumah Ibadah</td>
                    <td>
                        <!-- Lead to update form -->
                        <center>
                        <form action="{% url 'trigger_tiga:form-update-kategori-penggalangan-dana' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u">
                            <input type="submit" class="btn btn-primary btn-sm" value="Update">
                        </form>
                        </center>
                    </td>
                    </tr>

                <tr>
                    <td><center>3</center></td>
                    <td>Bencana</td>
                    <td>
                        <!-- Lead to update form -->
                        <center>
                        <form action="{% url 'trigger_tiga:form-update-kategori-penggalangan-dana' %}" method="get">
                            <input type="hidden" id="id_u" name="id_u">
                            <input type="submit" class="btn btn-primary btn-sm" value="Update">
                        </form>
                        </center>
                    </td>
                    </tr>
        </table>
    </div>
    <form action="{% url 'trigger_tiga:form-create-kategori-penggalangan-dana' %}" method="get">
        <input type="hidden" id="id_u" name="id_u">
        <input style="margin-left: 1055px;" type="submit" class="btn btn-success btn-sm" value="Tambah">
    </form>
{% endblock %}