bisasesama/urls.py
from django.contrib import admin
from django.urls import path, include
import beranda.urls as beranda

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('trigger_dua/', include('trigger_dua.urls', namespace='trigger_dua')),
    path('trigger_tiga/', include('trigger_tiga.urls', namespace='trigger_tiga')),
    path('pengguna/', include('pengguna.urls', namespace='pengguna')),
    path('trigger_empat/', include('trigger_empat.urls', namespace='trigger_empat')),
    path('login/', include('login.urls', namespace='login')),
    path('trigger_lima/', include('trigger_lima.urls', namespace='trigger_lima')),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = [
    path("", login, name="login"),
    path("logout/", logout, name="logout"),

]
    # path("form_donasi/", form_donasi, name="form_donasi"),
    # path("donasi/read_donasi", read_donasi, name="read_donasi"),
    # path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),

pengguna/urls.py
from django.urls import path
from .views import *

app_name = 'pengguna'

urlpatterns = [
    path("register", register, name="register"),
    path("admin", form_admin, name="admin"),
    path("penggalang_dana", form_pd, name="penggalang_dana"),
    path("penggalang_dana/individu", form_pd_individu, name="pd_individu"),
    path("penggalang_dana/organisasi", form_pd_organisasi, name="pd_organisasi"),
    path("profil_pengguna", profil_pengguna, name="profil-pengguna"),
    path("daftar-pengguna-admin", read_daftar_pengguna_admin, name="daftar-pengguna-admin"),
    path("daftar-pengguna-admin-afterverif", read_daftar_pengguna_admin_afterverif, name="daftar-pengguna-admin-afterverif"),
    path("profil-pengguna-individu-adminview", profil_pengguna_individu_adminview, name="profil-pengguna-individu-adminview"),
    path("profil-pengguna-organisasi-adminview", profil_pengguna_organisasi_adminview, name="profil-pengguna-organisasi-adminview"),
    path("daftar-pengguna-admin-verif", verifikasi_pengguna, name="daftar-pengguna-admin-verif"),
    path("logout", logout, name = "logout"),
    path("login", login, name = "login"),
    


]

trigger_dua/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_dua'

urlpatterns = [
    path("form_kategori/", form_kategori, name="form_kategori"),
    path("form_kategori/create_pasien", form_pasien, name="form_pasien"),
    path("form_kategori/cek_pasien", cek_pasien, name="cek_pasien"),
    path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),
    path("penggalangan_dana/detail", read_pdd, name="read_pdd"),
    path("penggalangan_dana/create", form_penggalangan_dana, name="create_pdd"),
    path("penggalangan_dana/delete/", delete_penggalangan_dana, name="delete_pdd"),
    path("penggalangan_dana/cairkan", cairkan_pdd, name="cairkan_pdd"),
    path("komorbid/create/", create_komorbid, name="create_komorbid"),
    path("komorbid/update/(?P<id>[^/]+)$/(?P<penyakit>[^/]+)$/", update_komorbid, name="update_komorbid"),
    path("komorbid/delete/(?P<id>[^/]+)$/(?P<komorbid>[^/]+)$/", delete_komorbid, name="delete_komorbid"),
    path("komorbid/", read_komorbid, name="read_komorbid"),
]

trigger_empat/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_empat'

urlpatterns = [
    path("penggalangan_dana_POV_Pengguna/", cek_penggalangan_dana, name="read_halaman_penggalangan_dana"),
    path("form_donasi/", form_donasi, name="form_donasi"),
    path("donasi/read_donasi", read_donasi, name="read_donasi"),
    path("donasi/read_detail_donasi", read_detail_donasi, name="read_detail_donasi"),
    path('tambah_Wishlist',tambah_wishlist, name= 'tambah_wishlist'),
    path('delete_wishlist', delete_wishlist_donasi, name = 'delete_wishlist' ),
    # path("form_kategori/create_rumah_ibadah", form_rumah_ibadah, name="form_rumah_ibadah"),
    # path("form_kategori/cek_rumah_ibadah", cek_rumah_ibadah, name="cek_rumah_ibadah"),
    # path("penggalangan_dana/", read_pdd_pribadi, name="read_pdd_pribadi"),  
]

trigger_tiga/urls.py
from django.urls import path
from .views import *

app_name = 'trigger_tiga'

urlpatterns = [
    path("daftar-penggalangan-dana-admin", read_daftar_penggalangan_dana_admin, name="daftar-penggalangan-dana-admin"),
    path("daftar-afterverif-penggalangan-dana-admin", read_afterverif_penggalangan_dana_admin, name="daftar-afterverif-penggalangan-dana-admin"),
    path("detail1-daftar-penggalangan-dana", detail1_daftar_penggalangan_dana, name="detail1-daftar-penggalangan-dana"),
    path("detail2-daftar-penggalangan-dana", detail2_daftar_penggalangan_dana, name="detail2-daftar-penggalangan-dana"),
    path("update-penggalangan-dana", form_update_penggalangan_dana, name="form-update-penggalangan-dana"),
    path("form-verifikasi-penggalangan-dana", form_verifikasi_penggalangan_dana, name="form-verifikasi-penggalangan-dana"),
    path("read-kategori-penggalangan-dana-admin", read_kategori_penggalangan_dana_admin, name="read-kategori-penggalangan-dana-admin"),
    path("form-create-kategori-penggalangan-dana", form_create_kategori_penggalangan_dana, name="form-create-kategori-penggalangan-dana"),
    path("form-update-kategori-penggalangan-dana", form_update_kategori_penggalangan_dana, name="form-update-kategori-penggalangan-dana"),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    </head>
    <body style="background-color:white;">
        <div>
            {% include 'navbar.html' %}
            {% include 'messages.html' %}
            {% block content %}

            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="  crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav style="background-color:#03045e" class="navbar navbar-expand-lg">
    <div class="container-fluid d-flex mr-auto">
        <a class="navbar-brand text-white" href="{% url '' %}">
            <i class="d-inline-block align-center fa fa-heart text-white"></i>
            BisaSesama
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav justify-content-start">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Penggalangan Dana
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% if request.session.role == 'PENGGALANG_DANA' %}
            <a class="dropdown-item " href="{% url 'trigger_dua:form_kategori' %}">Buat Penggalangan Dana</a>
            {% endif %}

            {% if request.session.role == 'ADMIN' %}
            <a class="dropdown-item " href="{% url 'trigger_tiga:read-kategori-penggalangan-dana-admin' %}">Kategori Penggalangan Dana</a>

            <a class="dropdown-item " href="{% url 'trigger_tiga:daftar-penggalangan-dana-admin' %}">Daftar Penggalangan Dana - Admin</a>
            {% endif %}
            {% if request.session.role == 'PENGGALANG_DANA' %}
            <a class="dropdown-item " href="{% url 'trigger_empat:read_halaman_penggalangan_dana' %}">Daftar Penggalangan Dana - Pengguna</a>
            {% endif %}
            <a class="dropdown-item " href="{% url 'trigger_dua:read_komorbid' %}">Kelola Penyakit Komorbid</a>

        </div>
        </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Data Penggalang Dana
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item " href="{% url 'trigger_dua:read_pdd_pribadi' %}">Daftar Penggalangan Dana Pribadi</a>
        </div>
        </li>

        {% if request.session.role_pdd == 'INDIVIDU' %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Donasi
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item " href="{% url 'trigger_empat:read_donasi' %}">Daftar Donasi</a>
            </div>
        </li>
        {% endif %}

        </ul>
        </div>
        {% if request.session.role == 'ADMIN' %}
        <a style="font-size: medium;" class="navbar-brand text-white" href="{% url 'pengguna:daftar-pengguna-admin' %}">
            <i class="d-inline-block align-center fa text-white"></i>
            Lihat Daftar Pengguna
        </a>
        {% endif %}
        {% if request.session.email %}
        <a style="font-size: medium;" class="navbar-brand text-white" href="{% url 'pengguna:profil-pengguna' %}">
            <i class="d-inline-block align-center fa text-white"></i>
            Profil
        </a>
        <a style="font-size: medium;" class="navbar-brand text-white" href="{% url 'login:logout' %}">
            <i class="d-inline-block align-center fa text-white"></i>
            Log out
        </a>
        {% else %}
        <a style="font-size: medium;" class="navbar-brand text-white" href="{% url 'login:login' %}">
            <i class="d-inline-block align-center fa text-white"></i>
            Login
        </a>
        <a style="font-size: medium;" class="navbar-brand text-white" href="{% url 'pengguna:register' %}">
            <i class="d-inline-block align-center fa text-white"></i>
            Register
        </a>
        {% endif %}
    </div>
</nav>